service: dynamo-scheduled-backup

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:CreateBackup"
      Resource: "*"

functions:
  backupDB:
    handler: src/backup.handler
    name: backup-dynamodb
    description: A scheduled lambda that performs a database backup for a DynamoDB table.
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - schedule: rate(1 minute)

    environment:
      DYNAMODB_TABLE_NAME: important-data
